name: main

# 触发workflow的条件
on:
  push:
    branches: [master]  # 只有 master 分支发生 push 事件时才会触发 workflow
  pull_request:
    branches: [master]  # 只有 master 分支的 pull request 事件才会触发 workflow

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境为最新的 Ubuntu 虚拟机
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 安装 Node.js
      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12  # 指定 Node.js 版本
          cache: 'npm'  # 使用 npm 缓存

      # 3. 安装 pnpm
      - name: 安装 pnpm
        run: npm install -g pnpm  # 全局安装 pnpm

      # 4. 安装项目依赖
      - name: 安装依赖
        run: pnpm i  # 使用 pnpm 安装依赖

      # 5. 构建项目
      - name: 打包项目
        run: pnpm run build  # 执行构建命令

      # 6. 压缩构建后的文件
      - name: 压缩构建文件
        run: tar -czf dist.tar.gz ./dist  # 将 dist 目录压缩为 dist.tar.gz

      # 7. 上传压缩文件到服务器
      - name: 上传压缩文件
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} scp -o StrictHostKeyChecking=no dist.tar.gz root@182.92.201.19:/www/wwwroot/community/
        env:
          REMOTE_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}  # 从 secrets 中获取服务器密码

      # 8. 在服务器上解压文件并删除压缩包
      - name: 解压文件并清理
        run: |
          sshpass -p ${{ secrets.DEPLOY_PASSWORD }} ssh -o StrictHostKeyChecking=no root@182.92.201.19 "tar -xzf /www/wwwroot/community/dist.tar.gz -C /www/wwwroot/community/ && rm /www/wwwroot/community/dist.tar.gz"
        env:
          REMOTE_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}  # 从 secrets 中获取服务器密码
